# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.4.0
group=fonnymunkey
java_version=21

# Common
minecraft_version=1.21.1
mod_name=SimpleHats
mod_author=fonnymunkey
mod_id=simplehats
license=Code: MIT, Assets: ARR
credits=fonnymunkey, ArtsyDy, BluSpring
description=Adds simple, customizable, cosmetic hats.
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.103.0+1.21.1
fabric_loader_version=0.16.5

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.62
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
accessories_version=1.1.0-beta.16+1.21.1
owo_version=0.12.15+1.21
owo_neoforge_version=0.12.15-beta.9+1.21