# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.4.0
group=fonnymunkey
java_version=25

# Common
minecraft_version=26.1.2
mod_name=SimpleHats
mod_author=fonnymunkey
mod_id=simplehats
license=Code: MIT, Assets: ARR
credits=fonnymunkey, ArtsyDy, BluSpring
description=Adds simple, customizable, cosmetic hats.
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1.2-1

# Fabric
fabric_version=0.151.0+26.1.2
fabric_loader_version=0.19.2

# Forge
forge_version=64.0.9
forge_loader_version_range=[64,)

# NeoForge
neoforge_version=26.1.2.75
neoforge_loader_version_range=[5,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
# TODO: Update Accessories when it's available
accessories_version=1.4.3-beta+1.21.10
owo_version=0.13.0+26.1
owo_neoforge_version=0.12.28+1.21.10

# https://modrinth.com/mod/trinkets-updated/versions
trinkets_version=4.0.0-beta.2+26.1
# https://modrinth.com/mod/curios/versions
curios_version=15.0.0-beta.2+26.1.2