# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.4.0a
group=fonnymunkey
java_version=17

# Common
minecraft_version=1.20.1
mod_name=SimpleHats
mod_author=fonnymunkey
mod_id=simplehats
license=Code: MIT, Assets: ARR
credits=fonnymunkey, ArtsyDy, BluSpring
description=Adds simple, customizable, cosmetic hats.
minecraft_version_range=[1.20.1, 1.22)

parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.1.47
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
accessories_version=1.0.0-beta.47+1.20.1
cloth_version=11.1.118