plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
	repositories {
		maven { url = "https://maven.wispforest.io/releases" }
        maven { url 'https://maven.su5ed.dev/releases' }
        maven {
            name = "TheIllusiveC4"
            url = "https://maven.theillusivec4.top/"
        }
	}
	dependencies {
        annotationProcessor implementation("io.wispforest:owo-lib-neoforge:${owo_neoforge_version}")
        compileOnly("io.wispforest:accessories-neoforge:${accessories_version}")

        compileOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}:api")
        runtimeOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}")
        implementation("eu.pb4:trinkets:${trinkets_version}")
	}
}

sourceSets.main.resources { srcDir 'src/generated/resources' }